# Generated by Django 4.2 on 2024-05-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.IntegerField(max_length=8)),
                ('contact_method', models.CharField(max_length=256)),
                ('university', models.CharField(max_length=256)),
                ('availability', models.CharField(max_length=1024)),
                ('resume', models.CharField(max_length=1024)),
                ('about_me', models.CharField(max_length=1024)),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='ryderz.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.IntegerField(max_length=8)),
                ('contact_method', models.CharField(max_length=256)),
                ('availability', models.CharField(max_length=1024)),
                ('about_me', models.CharField(max_length=1024)),
                ('subjects', models.ManyToManyField(blank=True, related_name='students', to='ryderz.subject')),
                ('tutors', models.ManyToManyField(blank=True, related_name='students', to='ryderz.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ryderz.student')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ryderz.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='ryderz.student')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='ryderz.tutor')),
            ],
        ),
    ]
