# Generated by Django 4.2 on 2024-05-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryderz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='phone_number',
        ),
    ]
