# Generated by Django 4.2 on 2024-05-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryderz', '0004_alter_student_birthday_alter_tutor_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
